# Dockerfile.api
FROM python:3.9-slim

WORKDIR /app

#Install dependencies for the API Gateway
RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

# We need requests to talk to other containers
RUN pip install fastapi uvicorn requests pandas codecarbon --no-cache-dir
RUN pip install --no-cache-dir "streamlit>=1.37.0" plotly


# Copy the source code
COPY src/ /app/src/
# Copy config if it exists in root
COPY config.py /app/
COPY models/ /app/models/


EXPOSE 8501

# Health check (Streamlit health endpoint)
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
  CMD curl --fail http://localhost:8501/_stcore/health || exit 1
  
CMD ["streamlit", "run", "src/gui/app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]